{{< include common.qmd >}}

# Introduction

C'est dans le cadre de mon M1 en biologie végétale tropicale (BioGet) à l'université Montpellier que j'ai entreprit le stage de recherche qui va vous être présenté dans ce mémoire. Celui-ci s'est déroulé sur le campus montpelliérain d'AgroParisTech ( co-pilote de mon parcours de M1). Ce campus regroupe plusieurs formations sur les écosystèmes forestiers et de la gestion de l'eau, ainsi que quatre pôles de recherches comme l'UMR "Territoires, environnement, télédétection et information spatiale". Lors de mon stage j'ai justement utilisé des informations spatiales afin d'analyser la biodiversité forestière tropicale.

Les vagues de chaleur éprouvantes qui ont touché la France fin juin 2026 nous ont confronté à la triste réalité du réchauffement planétaire et ses conséquences directes. Les forêts tropicales, poumons vert de la planète, de part leur extrême biodiversité, constituent autant une barrière à ce réchauffement que les premières cibles de celui-ci. Il devient plus qu’urgent de les préserver, or préservation va de paire avec connaissance. L’étude et la compréhension des ces milieux complexes et mystérieux est un vent d’espoir ou au moins l’une des pales du ventilateur qui nous sauvera de cette fournaise.

Afin de mieux appréhender la diversité tropicale, @wiegand2007 Pose les bases du calcul des "ISAR", des courbes d'accumulation spatiales, spécifiques à une seule espèce. Le sujet de mon stage porte sur ces mesures d’accumulation de la diversité et leur apport dans la compréhension des processus d’assemblage des communautés.

## État de l'art

### Forêts de Guyane

Les forêts tropicales représente 45% des forêts du globe. La Guyane françaises, elle, en est couverte à 96% @fao2025 et compte quelque 1700 essence d'arbres. Ces forêts appartiennent au “bouclier Guyanais”,aussi appelé “plateau des guyanes” c’est l’un des plus ancien massif montagneux de la planète. Il se compose de trois cratons précambrien formant de nombreux reliefs érodés et est caractérisé par des sols acides et pauvres en micronutriments @molino2022. Situé au nord-est du continent sud-américain, il traverse 6 pays : le Venezuela, le Guyana, le Brésil, le Suriname, la Colombie et la Guyane française (objets de notre études). La géologie du bouclier varie en fonction du pays, ainsi au Venezuela on trouve des hauts plateaux avec des reliefs culminant à 3000m alors que l’altitude en Guyane française est comprise entre 0 et 300m. De plus au cours de son histoire géologique, des pénétration d’eau dans les terres (du à l’élévation du niveaux des mers lors des périodes de réchauffement climatiques) ont participes à l’isolation du plateau des guyanes du bassin amazonien expliquant en partie son taux d’endémisme élevé (on en retrouve une soixantaine clairement identifiée rien qu’en Guyane française @geyer2020 .

La Guyane se caractérise par un climat équatorial humide qui voit d’effiler 4saisons, petite et grande saison sèche et petite et grande saison humide, avec des températures qui varient faiblement autour d’une moyenne de 27 dégrées et des précipitations moyennes annuelles qui varient de 2000 à 4000 mm.an^-1^. Bien que les perturbations météorologiques soit rares, ce territoire n’est nullement épargné par le chaufferette climatique, avec une augmentation moyenne de 1,4 dégrée entre 1955 et 2009 @météofrance. Avec ses 14 bassins versant, représente par des grand fleuves comme yapock ou le Maroni, qui sont autant de voies de pénétration dans la forêt, le système hydrologique joue un grand rôle dans la topographie guyanaise @observatoire_des_forêt_française .

La préservation des forêts de Guyane française est remarquables, 95% de ses forêts sont considérées comme primaires et nullement fragmentées @fao2025 . La faible population et sa répartition très localisée sur les régions côtières en est la cause principale. La Guyane étant un département français, elle se repose beaucoup sur des importations ce qui limite les besoins d’exploitation de ses propres ressources. De plus, des politiques de préservation misent en place dans les dernières années aide à maintenir l’état des forêts et en protéger la diversité @molino2022.

La forêt guyanais est décrite comme une mosaïque d’écosystèmes, si bien que chaque hectare se caractérise par une cohorte d’espèces qui peut être radicalement différent de l’hectare voisin @geyer2020 . On y retrouve de nombreux habitat allant des mangroves (avec seulement une dizaine d’espèces d’arbres) aux forêts des plateaux élevés, en passant par les forêt des basses vallées fluviales, forêts des collines irrégulières, forêts littorales sur cordons sableux, …La répartition en abondance et au sein des famille est très hétéroclite, les huit familles prédominantes (50% des espèce) sont : les Leguminosae, Lauraceae, Myrtaceae, Sapotaceae, Chrysobalanaceae, Annonaceae, Melastomataceae et Rubiaceae @molino2022 . D’un autre coté on retrouve une quarantaine de famille qui ne compte que 5 espèces ou moins.

### Techniques d'évaluation de la biodiversité

Définie comme “Variabilité des organismes vivants de toute origine y compris, entre autres, les écosystèmes terrestres, marins et autres écosystèmes aquatiques et les complexes écologiques dont ils font partie; cela comprend la diversité au sein des espèces et entre espèces ainsi que celle des écosystèmes” lors de la conférence sur la diversité biologique des nations unies de 1992 @NationUnies_convention_1992, la biodiversité est le socle de l’écologie actuelle.

L'évalutation de la biodiversité est une démarche qui requière une connaissances importante des mécanismes et dynamiques en place dans les écosystèmes. Cette évaluation est cependant plus qu'indispensable à la préservation de ceux-ci, car on ne peut protéger ce qu’on ne comprend pas. Les forêts tropicales et notamment celle de Guyane, par leur complexité et leur dynamique ont attiré des siècle durant, les scientifiques qui ont cherché à percevoir les mystères de la faune et la flore qui les composent. Ils ont inventoriées, mesurés, calculer des indices, optimisé les techniques de mesures dans l’espoir de mieux appréhender ces forêts. L’évaluation de la biodiversité est d’autant plus urgente qu’elle s’érode à une vitesse grand V. Les pressions anthropiques locales (certes relativement faibles en Guyane) mais aussi leurs répercussions à l’échelle planétaire causent de l’extinction de nombreuses espèces et de la dégradation rapide, parfois irréversibles des habitats naturels @ipbes_rapport_2020.

On considère généralement 3 niveaux de biodiversité : diversité génétique ( = intra-spécifique), spécifique (=interspécifique) et écosystémique @NationUnies_convention_1992. Bien que les deux autres autres niveaux soit extrêmement intéressants, on s’est focalisé ici sur la diversité spécifique. Elle étudie la nature (diversité fonctionnelle), l’abondance et le nombre d’espèces présentes sur terre @magurran2003. Dans le contexte des forêts guyanaises la diversité génétique mériterait à être plus étudiée de part les informations qu’elles fournis sur les dynamique d’évolution des population et leur possibles adaptation aux perturbation climatique à venir, malheureusement mon stage ne dure que 2mois…

Pour analyser la biodiversité spécifique, on utilise les données obtenues lors d’échantillonnages sur le terrain, ils permettent de rendre compte de la biodiversité globale sans avoir à la mesurer entièrement. En milieu forestier on mets en place des parcelles des quelques hectares, délimitées par des quadras dans lequel on inventorie chaque plantes/arbres. Des “simples” techniques d’inventaires sur le terrains, on peut utiliser aujourd’hui des images satellites ou des modèles statistique pour évaluer la biodiversité.

Dans le cadre de notre stage on mobilisé 2 mesures de diversité qui sont la base du calcul d'indices complexes, spécifique à certaines question biologiques :

- L’abondance soit le nombre d’individus par espèce

- La richesse spécifiques soit le nombres d’espèces différentes

Le milieu tropical est particulier car il est très dense, ce qui rend la délimitation des parcelles et la circulation sur le terrain difficile. De plus l’identification est rendue difficile par l’extrême diversité des taxons, le manque de caractères et description des espèces et les nombreuses espèces qu’il reste à identifier.

Il existe de nombreux indicateurs adapté à l’évaluation de la biodiversité. Ces indicateurs permettent de quantifier avec méthodologie la biodiversité permettant sa mesure objective et la simplification de données extrêmement complexes @UICN2014 . Il est important de choisir un ou plusieurs indices adapté à ses problématiques biologiques. Parmi ces indicateurs on trouve des indices comme Simpson ou Shannon, calculés à partir des données d’abondance et de richesse spécifiques, je vous renvoi aux matériels et méthodes pour ceux utilisé lors du stage.

Les courbes d’accumulation attestent elles aussi de la diversité d’une localité @gotelli2001. Elles sont utilisées pour faire une approximation du nombre d’espèces d’un échantillon sans avoir à en conaitres chaque individus. Pour cela, on accroît petit à petit le nombre d’individus mesurés créant ainsi une courbe d’accumulation qui atteint bien souvent un plateau. Dans notre stage, ces courbes d’accumulation on été quelque peu transformées selon une démarche développée par @wiegand2007 pour rendre compte de l’effet d’une espèces sur la diversité environnante (voir mat & med pour développement).

## Objectifs du stage

Le stage à pour objectif de comprendre les apports des mesures d’accumulation de la diversité à la compréhension des processus d’assemblage des communautés dans la forêt guyanaise. Par comprendre on entend d’abord un travail bibliographique afin de s’approprier les notions développé par @wiegand2007 puis une application de ses notions sur des jeux de données complexes des forêt tropicales. On cherchera à approfondir ces méthodes de calcul de courbes d’accumulation avec l’intégration d’indices de diversité complexes, tel que Simpson ou des notion de distance phylogénétique et fonctionnelle. Grace à ces courbes d’accumulation spécifique, on cherche à attester du potentiel “accumulateur” ou “repoussoir” de diversité des principales espèces guyanaises. Autrement dit, si une espèce a tendance à rassembler de nombreuses espèces différence dans son voisinage et donc “favoriser la diversité” ou si celle-ci a plutôt tendance à produire une diversité locale faible. Enfin on cherchera des applications possibles dans le domaine de la préservation, de l’économie ou même du social.

## Plan général de la démarche

La première partie du stage consista en un travail bibliographique. Les notions de diversité inhérentes aux forêts tropicales humides furent passées en revue, avec un zoom sur le cas des forêts de Guyane française. On se renseigna aussi brièvement sur les différentes manières de mesurer la biodiversité (indicateurs, inventaires, indices, taxonomie, …) . Et enfin le sujet spécifique des courbes d’accumulation par espèce et locales, abrégé “ISAR”, fut abordé en prenant appuis sur les articles développant ces mêmes mesures : @wiegand2007 et @wiegand2017 .

La deuxième partie, une fois toutes les notions comprises, fut une prise en main de celle-ci à travers les données du site de Paracou (mat & med ). Au moyen du logiciel Rstudio, les Isars d’un grand nombres d’espèces d’arbres furent calculées, nous permettant de classer les espèces entre accumulatrices de biodiversité et repoussoir. La création de fonctions simplifia grandement les calculs qui sont relativement longs et complexes.

Les résultat obtenus furent ensuite analysé avec un focus sur certaines espèces d’intérêt allant de paire avec une recherche sur les possibles applications futures et/ou le développement et la pertinence de la méthode des Isars.
