# Remerciements {.unnumbered}

Merci aux secrétariat d’APT, de m’avoir laisser rentrer quand mon QR code marchait pas (assez souvent). Nos discussions légères (loin de moi l’idée de connoter ce mot négativement, elles sont essentielles aux rapports sociaux) m’ont permis de sortir la tête du guidon, comme on dit dans le jargon.

Merci aux ouvriers du chantier d’APT, travailleur de l’ombre (ou plutôt du soleil) qui sous des chaleurs abominables ont oeuvré à rendre mon cadre de travail plus agréable. Il m’est arrivé tout de même de me plaindre du bruit, mais l’intention n’était guère dirigée contre ces ouvriers aguerris.

Merci à Laura Iovene pour avoir préparé des données utilisables et avoir réduit une bonne partie de mon temps de travail en faisant je ne sais quelle magie.

Merci aux fondateur de jetpunk et pédantix, qui ont distrait des millier d’étudiants de leur classes et je l’avoue m’ont distraite de mon stage (occasionnellement) le temps de pauses bien méritées.

Un immense merci à Marlène Kameni Tcheumaleu, ma partenaire de stage, cette rencontre est un cadeau si précieux. J’aurais aimé avoir pu en profiter dès le début de l’année et continuer d’en profiter encore en M2 (malheureusement ou plutôt fort heureusement, je décollerai pour la Guyane). La personne que j’ai découvert pendant ce stage est une perle rare. Merci pour ton ouverture sur le monde, pour ta gentillesse, ton humour, tes avis et tes réactions tranchées mais justes. Merci d’avoir vu en moi une amie et une confidente de ton quotidien (pas toujours facile). De m’avoir fait toucher du doigt la vie d’une immigrée en France et ouvert les yeux sur un continent que l’on ne reconnaît pas à sa juste valeur. Je te souhaite tout le bonheur du monde.

Merci à mon tuteur de stage Monsieur Eric Marcon, qui fut aussi mon professeur au cours de l’année. Ce stage et ce rapport n’aurait jamais été possible sans lui. Premièrement car il m’a gracieusement trouvé un stage (la ou j’avais échoué). Mais surtout car c’est toutes ses précieuses explications qui m’ont permis d’avoir les outils pour prendre en main le sujet et le comprendre. Merci beaucoup pour le temps (qui se fait très précieux en ce bas monde), la patience et la confiance que vous m’avez accordé.

Merci à mes amis et mes parents qui m’ont permis et me permettent encore de rester joyeuse dans les bons comme dans les moment plus difficiles. Merci de m’avoir soutenue et encouragé dans l’écriture de ce rapport qui pour moi fut loin d’être une tache aisée.

Et je finirai sur une citation si justement dite qu’il faudrait tout à chacun, se la répéter au moins une fois par jour :

“*Last but not least, I want to thank me. I want to thank me for believing in me, I want to thank me for doing all this hard work. I wanna thank me for having no days off. I wanna thank me for never quitting. I wanna thank me for always being a giver and trying to give more than I receive. I wanna thank me for trying to do more right than wrong. I wanna thank me for being me at all times* “ Snoop Dogg, 2018 ( @SnoopDogg)

Maria BRICE

<!--# Ne pas supprimer le code ci-dessous qui produit la table des matières. Supprimer la liste des tableaux si elle est inutile -->

```{=latex}
%Table des matières
\tableofcontents
%Liste des tableaux
\listoftables
% Liste des figures
\listoffigures
```
